main:
  home:
    path: /
    select: ^\/home.*$
    auth: out
  buffer:
    path: /twitter/
    select: ^\/twitter.*$
    auth: in
  account_settings:
    path: /dashboard/settings/account
    select: ^\/dashboard/settings/account.*$
    auth: in
  twitter_settings:
    path: /dashboard/settings/twitter
    select: ^\/dashboard/settings/twitter.*$
    auth: in
  sign_in:
    path: /users/sign_in
    select: ^\/users\/sign_in$
    auth: out
  sign_up:
    path: /users/sign_up
    select: ^\/users\/sign_up$
    auth: out
  sign_out:
    path: /users/sign_out
    select: ^\/users\/sign_out.*$
    auth: in
  plans:
    path: /plans
    select: ^\/plans.*$
