defaults: &defaults
  adapter: mysql2
  host: localhost
  reconnect: false
  username: root
  password: 
  pool: 5

development:
  <<: *defaults
  database: tbuff_dev

test:
  <<: *defaults
  database: tbuff_test

production:
  <<: *defaults
  database: tbuff
