defaults: &defaults
  adapter: mysql
  host: localhost
  reconnect: false
  username: root
  password: 0p9o8i7u
  pool: 5

development:
  <<: *defaults
  database: tbuff_dev

test:
  <<: *defaults
  database: tbuff_test

production:
  <<: *defaults
  database: tbuff