common: &common
  app_name: "Tweet Buffer"
  twitter:
    key: "lKbJ5Wtlk010AbcaM6VA"
    secret: "KXBLw1vtuF6GtOjiaT27XUpWQoLA1bXoVo3usfE"
development:
  <<: *common
test:
  <<: *common
production:
  <<: *common
